### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by FernandoGarcia** [getyourguide/dependabutler#8]
Hi!

I'm trying to install this script but it is throwing errors.

Firstly I was unable to run `go install github.com/getyourguide/dependabutler/cmd/dependabutler@latest`, so I did `go get -u github.com/getyourguide/dependabutler/cmd/dependabutler `.

With the last command I got this errors:

```
❯ go get -u github.com/getyourguide/dependabutler/cmd/dependabutler
# github.com/getyourguide/dependabutler/internal/pkg/util
../../go/src/github.com/getyourguide/dependabutler/internal/pkg/util/util.go:47:35: syntax error: unexpected o644, expecting comma or )
# github.com/cloudflare/circl/math/fp25519
../../go/src/github.com/cloudflare/circl/math/fp25519/fp_generic.go:78:12: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp25519/fp_generic.go:79:12: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp25519/fp_generic.go:80:12: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp25519/fp_generic.go:81:12: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp25519/fp_generic.go:83:11: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp25519/fp_generic.go:84:11: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp25519/fp_generic.go:85:11: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp25519/fp_generic.go:86:11: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp25519/fp_generic.go:87:10: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp25519/fp_generic.go:106:12: undefined: bits.Sub64
../../go/src/github.com/cloudflare/circl/math/fp25519/fp_generic.go:106:12: too many errors
# github.com/cloudflare/circl/math/fp448
../../go/src/github.com/cloudflare/circl/math/fp448/fp_generic.go:117:12: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp448/fp_generic.go:118:12: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp448/fp_generic.go:119:12: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp448/fp_generic.go:120:12: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp448/fp_generic.go:121:12: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp448/fp_generic.go:122:12: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp448/fp_generic.go:123:12: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp448/fp_generic.go:125:11: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp448/fp_generic.go:126:11: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp448/fp_generic.go:127:11: undefined: bits.Add64
../../go/src/github.com/cloudflare/circl/math/fp448/fp_generic.go:127:11: too many errors
```
O.S.: Ubuntu 18.04
GO version: 1.10.4

Best regards.

**Comment by PhilippSieber** [comment]
Hi Fernando!

Thanks for reporting. It looks like you are using an older version of Go, which is not supported and causes the issues. Try with the latest version (1.20). 
We plan to provide a Dockerfile which provides the required environment and should be easy to use.

Regards, Philipp

**Comment by FernandoGarcia** [comment]
Hi!

Sorry for bother you but instructions are not clear to me.

I have updated go to 1.20.2 then run the command `go install github.com/getyourguide/dependabutler/cmd/dependabutler@latest`

The files were saved at `/home/fernandogarcia/go/src/github.com/getyourguide/dependabutler` but I don't know how to run the application.

`go dependabutler` will return `go dependabutler: unknown command`

`dependabutler` will return `zsh: command not found: dependabutler`

`go mod dependabutler` will return `go mod dependabutler: unknown command`

Thanks for your help.

**Comment by PhilippSieber** [comment]
Hi Fernando!

no problem, happy to help. We'll write a better intro / quick start later.

For now, you can use the tool as follows:

- clone/update the repo and cd into the dependabutler folder

- to scan a **local** directory, call:  
  `go run cmd/dependabutler/main.go -configFile dependabutler-minimal.yml -dir /path/to/repository`

- to scan a **remote** repo on GitHub:
   - get an API token from GitHub and set it as env variable: `export GITHUB_TOKEN=ghg_........`
   - `go run cmd/dependabutler/main.go -configFile dependabutler-minimal.yml -mode remote -org yourgithuborg -repo yourrepo`
   - both commands above will be in dry-run mode, nothing will be changed yet
   - to change things, add the `-execute true` option

dependabutler-minimal.yml is a minimal config file I just added. For more options/details, check dependabutler-sample.yml

Hope it helps. Feedback is very welcome, dependabutler is still work in progress.

Regards, Philipp

**Comment by FernandoGarcia** [comment]
Hi!

Thanks for you patience.

Now I seems working. I got this result : 

`INFO  No update needed.`

I'll try learn more about this subject.

Best regards.
